site_name: CherryHub
site_description: Math blog & code showcases
site_url: https://maracujadev.github.io

repo_url: https://github.com/maracujadev
repo_name: My GitHub Profile


theme:
    name: material
    font:
      code: Geist Mono
      text: Geist Mono
    palette:
      - scheme: default
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-night
          name: Switch to dark mode

      - scheme: slate
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

    features:
      - navigation.tabs
      - content.tooltips
      - search.suggest
    favicon: assets/favicon.png

copyright: "© Copyright 2026 maracujadev"

nav:
  - Homepage: index.md
  - Articles:
    - Blog Home: blog/index.md
  - CherryBot: cherrybot.md
  - About: about.md


plugins:
  - search
  - social:
      cards_layout_dir: layouts
      cards_layout: custom
      debug: false
  - blog:
      post_dir: blog/posts
      post_url_format: "{slug}"
      archive: false

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
#  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@mathyard
      name: Mathyard on Mastodon
    - icon: fontawesome/brands/github
      link: https://github.com/maracujadev
      name: Maracujadev on GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/metacyclinemachine/
      name: Metacyclinemachine on Instagram
    - icon: simple/letterboxd
      link: https://boxd.it/dCyNv
      name: Maracuja on Letterboxd
